import { Item } from "@/components/CartProvider";

export const navbar = [
  {
    label: "About",
    href: "intropage",
  },
  {
    label: "Brands",
    href: "type",
  },
  {
    label: "Products",
    href: "products",
  },
  {
    label: "History",
    href: "history",
  },
  {
    label: "Overview",
    href: "overview",
  },
];

export const footerLinks = [
  {
    title: "Useful Links",

    link: [
      {
        href: "intropage",
        label: "About",
      },
      {
        href: "type",
        label: "Brands",
      },
      {
        href: "products",
        label: "Products",
      },
      {
        href: "history",
        label: "History",
      },
      {
        href: "overview",
        label: "Overview",
      },
    ],
  },
];

export const textContent = [
  {
    head: "Innovation and Creativity:",
    ptag: " Evaluate the uniqueness and creativity of the solution. Consider whether it addresses a real-world problem in a novel way or introduces innovative features.",
  },
  {
    head: "Functionality:",
    ptag: "  Assess how well the solution works. Does it perform its   intended functions effectively and without major issues? Judges would consider the completeness and robustness of the solution.",
  },
  {
    head: "Impact and Relevance:",
    ptag: " Determine the potential impact of the solution in the real world. Does it address a significant problem, and is it relevant  to the target audience? Judges would assess the potential social,  economic, or environmental benefits.",
  },
  {
    head: "Technical Complexity:",
    ptag: "  Evaluate the technical sophistication of the solution.  Judges would consider the complexity of the code, the use of advanced technologies or algorithms, and the scalability of the solution.",
  },
  {
    head: "Adherance to Hackathon Rules:",
    ptag: " Adherence to Hackathon Rules: Judges will Ensure that the team adhered to the rules and guidelines of the hackathon, including deadlines, use of specific technologies or APIs, and any other competition-specific requirements. ",
  },
];

export const text = [
  "Can I work on a project I started before the hackathon?",
  "What happens if I need help during the hackathon?",
  "What happens if I don't have an idea for a project?",
  "Can I join a team or do I have to come with one?",
  "What happens after the hackathon ends",
  "Can I work on a project I started before the hackathon?",
];
export const Customers = [
  {
    img: "/babe.png",
    name: "Stone Schewazernega",
    text: "Car's hub is really a great e-commerce company, they really stand for what they do, i got a Mercedes benz C300 black, and it was really a nice ride 😊. Thank you car's hub",
  },
  {
    img: "/babe.png",
    name: "Sam Chevron",
    text: "At first when i heard of car's hub, i never knew they would be this true and transparent, i got a Toyota Supra GT, best of all my ride came to me looking so new. Thank car's hub😍 ",
  },
  {
    img: "/babe.png",
    name: "Vicky Devy",
    text: "Car's hub you guys are such wonderful company, i was referred by my friend, i was surprised and decided to try my luck, and today i own a Porsche carrera, thanks to car's hub 🥰",
  },
  {
    img: "/babe.png",
    name: "Abros Oyinbo",
    text: "At first i didn't want to comment or give a feedback but i had to do it to extend the good works of car's hub, i got a nice ride from this platform a Mercedes benz to be precised 😊",
  },
];
export const filterCars: Item[] = [
  {
    id: 1,
    name: "C300 black",
    img: "/balck_benz.png",
    class: "C class",
    model: "sport",
    price: 56,
    eng: "Twin turbo v8",
    spd: "30km/h",
    manufacturer: "Mercedes benz",
    drive: "RWD",
    hp: "350hp",
    color: "Black",
    stats: "Add to cart",
  },

  {
    id: 2,
    name: "Nismo Gt",
    img: "/nismo_gt.png",
    class: "No class",
    model: "sport",
    price: 45,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Nissan",
    drive: "RWD",
    hp: "300hp",
    color: "White",
    stats: "Add to cart",
  },
  {
    id: 3,
    name: "Maybach",
    img: "/maybach.png",
    class: "s class",
    model: "concept",
    price: 196,
    eng: "Twin turbo v8",
    spd: "60km/h",
    manufacturer: "Mercedes benz",
    drive: "RWD",
    hp: "400hp",
    color: "Shining black",
    stats: "Add to cart",
  },
  {
    id: 4,
    name: "Toyota supra",
    img: "/Toyota_gt.png",
    class: "No class",
    model: "sport",
    price: 45,
    eng: "v8",
    spd: "40km/h",
    manufacturer: "Toyota",
    drive: "RWD",
    hp: "500hp",
    color: "Gray",
    stats: "Add to cart",
  },

  {
    id: 5,
    name: "Mazda pro",
    img: "/mazda_pro.png",
    class: "No class",
    model: "sport",
    price: 59,
    eng: "v6",
    spd: "50km/h",
    manufacturer: "Mazda",
    drive: "RWD",
    hp: "300hp",
    color: "White",
    stats: "Add to cart",
  },
  {
    id: 6,
    name: "C63 white",
    img: "/amg.png",
    class: "C class",
    model: "Sport",
    price: 106,
    eng: "Twin turbo v8",
    spd: "60km/h",
    manufacturer: "Mercedes benz",
    drive: "RWD",
    hp: "500hp",
    color: "Shining gray",
    stats: "Add to cart",
  },
  {
    id: 7,
    name: "Maybach s",
    img: "/white_benz.png",
    class: "S class",
    model: "luxury",
    price: 96,
    eng: "v8",
    spd: "60km/h",
    manufacturer: "Mercedes benz",
    drive: "RWD",
    hp: "450hp",
    color: "White",
    stats: "Add to cart",
  },
  {
    id: 8,
    name: "Lambo. Urus",
    img: "/urus.png",
    class: "No class",
    model: "sport_suv",
    price: 119,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Lamboghini",
    drive: "$WD",
    hp: "700hp",
    color: "Champagne Gold",
    stats: "Add to cart",
  },

  {
    id: 9,
    name: "C300 white",
    img: "/white.png",
    class: "c class",
    model: "sport",
    price: 86,
    eng: "Twin turbo v8",
    spd: "50km/h",
    manufacturer: "Mercedes benz",
    drive: "RWD",
    hp: "500hp",
    color: "White",
    stats: "Add to cart",
  },
  {
    id: 10,
    name: "Amg red C63",
    img: "/convertible.png",
    class: "C class",
    model: "Sport",
    price: 76,
    eng: "Super turbo v8",
    spd: "60km/h",
    manufacturer: "Mercedes benz",
    drive: "RWD",
    hp: "650hp",
    color: "Red",
    stats: "Add to cart",
  },
  {
    id: 11,
    name: "Maybach 2022",
    img: "/2022.png",
    class: "S class",
    model: "luxury",
    price: 67,
    eng: "Twin turbo",
    spd: "60km/h",
    manufacturer: "Mercedes benz",
    drive: "RWD",
    hp: "500hp",
    color: "Shining black",
    stats: "Add to cart",
  },
  {
    id: 12,
    name: "Mercedes E63",
    img: "/2018.png",
    class: "E class",
    model: "luxury",
    price: 59,
    eng: "Twin turbo",
    spd: "60km/h",
    manufacturer: "Mercedes benz",
    drive: "RWD",
    hp: "400hp",
    color: "Shining gray",
    stats: "Add to cart",
  },
  {
    id: 13,
    name: "Toyota",
    img: "/toyota.png",
    class: "No class",
    model: "Sport",
    price: 51,
    eng: "v6",
    spd: "30km/h",
    manufacturer: "Toyota",
    drive: "RWD",
    hp: "250hp",
    color: "Black",
    stats: "Add to cart",
  },
  {
    id: 14,
    name: "Amg gt",
    img: "/yellow_benz.png",
    class: "C class",
    model: "sport",
    price: 69,
    eng: "Super turbo b8",
    spd: "60km/h",
    manufacturer: "Mercedes benz",
    drive: "RWD",
    hp: "700hp",
    color: "Yellow",
    stats: "Add to cart",
  },

  {
    id: 15,
    name: "Supra Gt",
    img: "/supra.png",
    class: "No class",
    model: "sport",
    price: 65,
    eng: "Turbo chrged v8",
    spd: "60km/h",
    manufacturer: "Toyota",
    drive: "RWD",
    hp: "700hp",
    color: "Light brown",
    stats: "Add to cart",
  },

  {
    id: 16,
    name: "Amg gt",
    img: "/Amg-gt.png",
    class: "A class",
    model: "Sport",
    price: 96,
    eng: "Twin turbo v8",
    spd: "60km/h",
    manufacturer: "Mercedes benz",
    drive: "RWD",
    hp: "500hp",
    color: "Shining gray",
    stats: "Add to cart",
  },
  {
    id: 17,
    name: "Mazda MX",
    img: "/mazda_mx.png",
    class: "No class",
    model: "sport",
    price: 76,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Mazda",
    drive: "RWD",
    hp: "500hp",
    color: "Red",
    stats: "Add to cart",
  },
  {
    id: 18,
    name: "Nissan GTR",
    img: "/nissan_gt.png",
    class: "No class",
    model: "super sport",
    price: 90,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Nissan",
    drive: "4WD",
    hp: "800hp",
    color: "Ash gray",
    stats: "Add to cart",
  },
  {
    id: 19,
    name: "BMW m5",
    img: "/bmw-m5.png",
    class: "No class",
    model: "convertible",
    price: 100,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "BMW",
    drive: "RWD",
    hp: "500hp",
    color: "Original",
    stats: "Add to cart",
  },
  {
    id: 20,
    name: "Camry SE",
    img: "/camry_sport.png",
    class: "No class",
    model: "sport",
    price: 45,
    eng: "v8",
    spd: "40km/h",
    manufacturer: "Toyota",
    drive: "RWD",
    hp: "300hp",
    color: "Red",
    stats: "Add to cart",
  },
  {
    id: 21,
    name: "Mazda",
    img: "/mazda.png",
    class: "No class",
    model: "regular",
    price: 35,
    eng: " v6",
    spd: "30km/h",
    manufacturer: "Mazda",
    drive: "RWD",
    hp: "250hp",
    color: "As gray",
    stats: "Add to cart",
  },

  {
    id: 22,
    name: "black C63",
    img: "/mybenz.png",
    class: "c class",
    model: "sport",
    price: 77,
    eng: "Twin turbo v8",
    spd: "60km/h",
    manufacturer: "Mercedes benz",
    drive: "RWD",
    hp: "600hp",
    color: "White",
    stats: "Add to cart",
  },
  {
    id: 23,
    name: "BMW m5 GT",
    img: "/bmw_white.png",
    class: "No class",
    model: "sport",
    price: 55,
    eng: "Turbo charged v8",
    spd: "50km/h",
    manufacturer: "BWM",
    drive: "RWD",
    hp: "400hp",
    color: "Original",
    stats: "Add to cart",
  },
  {
    id: 24,
    name: "Corolla Black",
    img: "/toyota_black.png",
    class: "No class",
    model: "sport",
    price: 45,
    eng: "v8",
    spd: "60km/h",
    manufacturer: "Toyota",
    drive: "RWD",
    hp: "300hp",
    color: "Black",
    stats: "Add to cart",
  },
  {
    id: 25,
    name: "SE Black",
    img: "/camry_black.png",
    class: "No class",
    model: "sport",
    price: 55,
    eng: "v8",
    spd: "60km/h",
    manufacturer: "Toyota",
    drive: "RWD",
    hp: "300hp",
    color: "Black",
    stats: "Add to cart",
  },
  {
    id: 26,
    name: "Supra Gt",
    img: "/supra_pro.png",
    class: "No class",
    model: "super sport",
    price: 100,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Toyota",
    drive: "RWD",
    hp: "800hp",
    color: "Red",
    stats: "Add to cart",
  },
  {
    id: 27,
    name: "Lexus LFA",
    img: "/Lexus_LFA.png",
    class: "No class",
    model: "super sport",
    price: 120,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Lexus",
    drive: "RWD",
    hp: "700hp",
    color: "Blue",
    stats: "Add to cart",
  },
  {
    id: 28,
    name: "Supra GT",
    img: "/supra_gt.png",
    class: "No class",
    model: "sport",
    price: 90,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Toyota",
    drive: "RWD",
    hp: "600hp",
    color: "Gray",
    stats: "Add to cart",
  },
  {
    id: 29,
    name: "Amg gt C63",
    img: "/amg_cool.png",
    class: "c class",
    model: "sport",
    price: 99,
    eng: "Twin turbo v8",
    spd: "60km/h",
    manufacturer: "Mercedes benz",
    drive: "RWD",
    hp: "600hp",
    color: "Shining gray",
    stats: "Add to cart",
  },

  {
    id: 30,
    name: "Acura Gt",
    img: "/acura_sport.png",
    class: "No class",
    model: "super sport",
    price: 100,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Acura",
    drive: "RWD",
    hp: "900hp",
    color: "White",
    stats: "Add to cart",
  },
  {
    id: 31,
    name: "Lexus is350",
    img: "/is_350.png",
    class: "No class",
    model: "sport",
    price: 70,
    eng: "Turbo charged v8",
    spd: "50km/h",
    manufacturer: "Lexus",
    drive: "RWD",
    hp: "600hp",
    color: "Ash gray",
    stats: "Add to cart",
  },
  {
    id: 32,
    name: "Acura NSX",
    img: "/acura_nsx.png",
    class: "No class",
    model: "super sport",
    price: 100,
    eng: "Turbo charged v12",
    spd: "60km/h",
    manufacturer: "Acura",
    drive: "RWD",
    hp: "900hp",
    color: "Red",
    stats: "Add to cart",
  },
  {
    id: 33,
    name: "Nissan 350z",
    img: "/350z.png",
    class: "No class",
    model: "convertible",
    price: 55,
    eng: "v8",
    spd: "60km/h",
    manufacturer: "Nissan",
    drive: "RWD",
    hp: "300hp",
    color: "Black",
    stats: "Add to cart",
  },
  {
    id: 34,
    name: "Supra",
    img: "/toyota_blue.png",
    class: "No class",
    model: "sport",
    price: 65,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Toyota",
    drive: "RWD",
    hp: "500hp",
    color: "Blue",
    stats: "Add to cart",
  },
  {
    id: 35,
    name: "Mazda Gt",
    img: "/club.png",
    class: "No class",
    model: "sport",
    price: 45,
    eng: "Turbo charged v8",
    spd: "40km/h",
    manufacturer: "Mazda",
    drive: "RWD",
    hp: "300hp",
    color: "White",
    stats: "Add to cart",
  },
  {
    id: 36,
    name: "Lexus Gt",
    img: "/lexus_gt.png",
    class: "No class",
    model: "sport",
    price: 80,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Lexus",
    drive: "RWD",
    hp: "700hp",
    color: "White",
    stats: "Add to cart",
  },
  {
    id: 37,
    name: "Lambo. Sian",
    img: "/sian.png",
    class: "No class",
    model: "super sport",
    price: 300,
    eng: "Turbo charged v12",
    spd: "60km/h",
    manufacturer: "Lamboghini",
    drive: "RWD",
    hp: "1000hp",
    color: "Dark green",
    stats: "Add to cart",
  },
  {
    id: 38,
    name: "Aventador",
    img: "/aventador.png",
    class: "No class",
    model: "super sport",
    price: 200,
    eng: "Turbo charged v12",
    spd: "60km/h",
    manufacturer: "Lamboghini",
    drive: "RWD",
    hp: "1000hp",
    color: "Champagne Gold",
    stats: "Add to cart",
  },
  {
    id: 39,
    name: "Corolla",
    img: "/corolla.png",
    class: "No class",
    model: "regular",
    price: 45,
    eng: "v6",
    spd: "30km/h",
    manufacturer: "Toyota",
    drive: "RWD",
    hp: "300hp",
    color: "White",
    stats: "Add to cart",
  },
  {
    id: 40,
    name: "Corolla",
    img: "/toyota_black.png",
    class: "No class",
    model: "regular",
    price: 45,
    eng: "v6",
    spd: "30km/h",
    manufacturer: "Toyota",
    drive: "RWD",
    hp: "300hp",
    color: "Black",
    stats: "Add to cart",
  },
  {
    id: 41,
    name: "G-wagon",
    img: "/G-wagon.png",
    class: "G class",
    model: "luxury",
    price: 200,
    eng: "v12",
    spd: "50km/h",
    manufacturer: "Mercedes",
    drive: "4WD",
    hp: "500hp",
    color: "Black",
    stats: "Add to cart",
  },
  {
    id: 42,
    name: "Ferrari 458",
    img: "/458_yellow.png",
    class: "No class",
    model: "super sport",
    price: 150,
    eng: "v12",
    spd: "60km/h",
    manufacturer: "Ferrari",
    drive: "RWD",
    hp: "800hp",
    color: "Yellow",
    stats: "Add to cart",
  },
  {
    id: 43,
    name: "Benz",
    img: "/pick_up.png",
    class: "G class",
    model: "luxury",
    price: 100,
    eng: "v8",
    spd: "50km/h",
    manufacturer: "Mercedes",
    drive: "4WD",
    hp: "500hp",
    color: "Black",
    stats: "Add to cart",
  },
  {
    id: 44,
    name: "Audi",
    img: "/audi.png",
    class: "No class",
    model: "Hatchback",
    price: 60,
    eng: "v8",
    spd: "40km/h",
    manufacturer: "Audi",
    drive: "4WD",
    hp: "350hp",
    color: "Ash",
    stats: "Add to cart",
  },
  {
    id: 45,
    name: "D. Challenger",
    img: "/dodge.png",
    class: "No class",
    model: "sport",
    price: 90,
    eng: "v12",
    spd: "50km/h",
    manufacturer: "Dodge",
    drive: "RWD",
    hp: "500hp",
    color: "Ash gray",
    stats: "Add to cart",
  },
  {
    id: 46,
    name: "Audi R8",
    img: "/audi_r8.png",
    class: "No class",
    model: "sport",
    price: 70,
    eng: "v12",
    spd: "50km/h",
    manufacturer: "Audi",
    drive: "RWD",
    hp: "500hp",
    color: "Ash gray",
    stats: "Add to cart",
  },
  {
    id: 47,
    name: "Ferrari 458",
    img: "/ferrari_458.png",
    class: "No class",
    model: "super sport",
    price: 150,
    eng: "v12",
    spd: "60km/h",
    manufacturer: "Ferrari",
    drive: "4WD",
    hp: "700hp",
    color: "Red",
    stats: "Add to cart",
  },
  {
    id: 48,
    name: "Audi Sport",
    img: "/audi_sport.png",
    class: "No class",
    model: "super sport",
    price: 200,
    eng: "v12",
    spd: "60km/h",
    manufacturer: "Audi",
    drive: "RWD",
    hp: "700hp",
    color: "Red",
    stats: "Add to cart",
  },
  {
    id: 49,
    name: "Dodge 2020",
    img: "/dodge_2020.png",
    class: "No class",
    model: "sport",
    price: 100,
    eng: "v12",
    spd: "50km/h",
    manufacturer: "Dodge",
    drive: "4WD",
    hp: "500hp",
    color: "Black",
    stats: "Add to cart",
  },
  {
    id: 50,
    name: "D. Charger",
    img: "/dodge_charger.png",
    class: "N0 class",
    model: "sport",
    price: 90,
    eng: "v12",
    spd: "50km/h",
    manufacturer: "Dodge",
    drive: "RWD",
    hp: "500hp",
    color: "White",
    stats: "Add to cart",
  },
  {
    id: 51,
    name: "Audi Gt",
    img: "/audi_gt.png",
    class: "No class",
    model: "sport",
    price: 100,
    eng: "Turbo charged v8",
    spd: "50km/h",
    manufacturer: "Audi",
    drive: "RWD",
    hp: "500hp",
    color: "Red",
    stats: "Add to cart",
  },
  {
    id: 52,
    name: "D. charger",
    img: "/charger.png",
    class: "No class",
    model: "sport",
    price: 70,
    eng: "v8",
    spd: "50km/h",
    manufacturer: "Dodge",
    drive: "RWD",
    hp: "500hp",
    color: "Black",
    stats: "Add to cart",
  },
  {
    id: 53,
    name: "Porsche Gt",
    img: "/porsche.png",
    class: "No class",
    model: "Convertible",
    price: 100,
    eng: "Turbo charged v12",
    spd: "50km/h",
    manufacturer: "Porsche",
    drive: "RWD",
    hp: "600hp",
    color: "Black",
    stats: "Add to cart",
  },
  {
    id: 54,
    name: "BMW M5 Gold",
    img: "/bmw_gold.png",
    class: "No class",
    model: "sport",
    price: 100,
    eng: "v8",
    spd: "50km/h",
    manufacturer: "BMW",
    drive: "RWD",
    hp: "500hp",
    color: "Gold",
    stats: "Add to cart",
  },
  {
    id: 55,
    name: "Lexus LFA",
    img: "/lfa_2022.png",
    class: "No class",
    model: "sport",
    price: 100,
    eng: "Turbo charged v12",
    spd: "50km/h",
    manufacturer: "Lexus",
    drive: "RWD",
    hp: "500hp",
    color: "Blue",
    stats: "Add to cart",
  },
  {
    id: 56,
    name: "Porsche Carrera",
    img: "/carrera.png",
    class: "No class",
    model: "sport",
    price: 90,
    eng: "Turbo charged v12",
    spd: "50km/h",
    manufacturer: "Porsche",
    drive: "RWD",
    hp: "500hp",
    color: "Ash gray",
    stats: "Add to cart",
  },
  {
    id: 57,
    name: "BMW M4",
    img: "/bmw_m4.png",
    class: "No class",
    model: "sport",
    price: 60,
    eng: "v8",
    spd: "40km/h",
    manufacturer: "BMW",
    drive: "RWD",
    hp: "400hp",
    color: "Blue",
    stats: "Add to cart",
  },
  {
    id: 58,
    name: "Lexus",
    img: "/orange-car.png",
    class: "No class",
    model: "sport",
    price: 50,
    eng: "v8",
    spd: "40km/h",
    manufacturer: "Lexus",
    drive: "RWD",
    hp: "500hp",
    color: "Orange",
    stats: "Add to cart",
  },
  {
    id: 59,
    name: "BMW M8",
    img: "/bmw_m8.png",
    class: "No class",
    model: "sport",
    price: 100,
    eng: "v8",
    spd: "50km/h",
    manufacturer: "BMW",
    drive: "RWD",
    hp: "400hp",
    color: "Dark blue",
    stats: "Add to cart",
  },
  {
    id: 60,
    name: "Volkswagen",
    img: "/suv.png",
    class: "G class",
    model: "suv",
    price: 50,
    eng: "v8",
    spd: "40km/h",
    manufacturer: "Volkswagen",
    drive: "4WD",
    hp: "300hp",
    color: "Ash",
    stats: "Add to cart",
  },
  {
    id: 61,
    name: "Porsche",
    img: "/taycan.png",
    class: "No class",
    model: "super sport",
    price: 100,
    eng: "Turbo charged v12",
    spd: "60km/h",
    manufacturer: "Porsche",
    drive: "RWD",
    hp: "600hp",
    color: "Ash",
    stats: "Add to cart",
  },
  {
    id: 62,
    name: "Porsche Taycan",
    img: "/porsche_taycan.png",
    class: "No class",
    model: "super sport",
    price: 90,
    eng: "Turbo charged/electric v12",
    spd: "60km/h",
    manufacturer: "Porsche",
    drive: "RWD",
    hp: "600hp",
    color: "Ash",
    stats: "Add to cart",
  },
  {
    id: 63,
    name: "Porsche 911",
    img: "/turbo_car.png",
    class: "No class",
    model: "convertible",
    price: 60,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Porsche",
    drive: "RWD",
    hp: "500hp",
    color: "Black",
    stats: "Add to cart",
  },
  {
    id: 64,
    name: "Volkswagen",
    img: "/white_volks.png",
    class: "No class",
    model: "hatchback",
    price: 50,
    eng: "v6",
    spd: "30km/h",
    manufacturer: "Volkswagen",
    drive: "4WD",
    hp: "300hp",
    color: "White",
    stats: "Add to cart",
  },
  {
    id: 65,
    name: "Peugeot",
    img: "/peuheot_ash.png",
    class: "No class",
    model: "regular",
    price: 50,
    eng: "v8",
    spd: "50km/h",
    manufacturer: "Peugeot",
    drive: "4WD",
    hp: "300hp",
    color: "Shining Ash",
    stats: "Add to cart",
  },
  {
    id: 66,
    name: "Porsche 911",
    img: "/porsche_911.png",
    class: "No class",
    model: "super sport",
    price: 90,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Porsche",
    drive: "RWD",
    hp: "600hp",
    color: "Yellow",
    stats: "Add to cart",
  },
  {
    id: 67,
    name: "Porsche",
    img: "/porsche_red.png",
    class: "No class",
    model: "super sport",
    price: 80,
    eng: "Turbo charged v8",
    spd: "60km/h",
    manufacturer: "Porsche",
    drive: "RWD",
    hp: "600hp",
    color: "Red",
    stats: "Add to cart",
  },
  {
    id: 68,
    name: "Peugeot",
    img: "/peugeot_suv.png",
    class: "No class",
    model: "suv",
    price: 50,
    eng: "Electric v8",
    spd: "40km/h",
    manufacturer: "Peugeot",
    drive: "4WD",
    hp: "400hp",
    color: "Dark blue",
    stats: "Add to cart",
  },
  {
    id: 69,
    name: "Peugeot GT",
    img: "/peugeot_gt.png",
    class: "No class",
    model: "sport",
    price: 80,
    eng: "Turbo charged/electric v12",
    spd: "60km/h",
    manufacturer: "Peugeot",
    drive: "RWD",
    hp: "600hp",
    color: "Ash",
    stats: "Add to cart",
  },
  {
    id: 70,
    name: "Volkswagen",
    img: "/volks.png",
    class: "No class",
    model: "regular",
    price: 50,
    eng: "Electric v8",
    spd: "50km/h",
    manufacturer: "Peugeot",
    drive: "RWD",
    hp: "400hp",
    color: "Black",
    stats: "Add to cart",
  },
];
